sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Supplier
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
                products:
                    type: string
                    label: sylius.ui.products
                    path: countProducts
                state:
                    type: twig
                    label: sylius.ui.state
                    options: 
                        template: "Supplier/Grid/state.html.twig"
            actions: 
                 main: 
                     create:
                         type: create
                 item:
                     update:
                         type: update
                     delete:
                         type: delete
                     trust:
                         type: apply_transition
                         label: app.ui.trust
                         icon: star
                         options: 
                             link:
                                route: app_admin_supplier_trust
                                parameters: 
                                    id: resource.id
                             transition: trust
                             graph: app_supplier
                             class: yellow
